apiVersion: apps/v1
kind: Deployment
metadata:
  name: uebungsverwaltung-frontend
  labels:
    app: uebungsverwaltung
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uebungsverwaltung
  template:
    metadata:
      labels:
        app: uebungsverwaltung
    spec:
      containers:
        - name: uebungsverwaltung
          image: rg.fr-par.scw.cloud/namespace-uebungsverwaltung/uebungsverwaltung-nginx:v9
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: uebungsverwaltung
    tier: frontend
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer

