apiVersion: apps/v1
kind: Deployment
metadata:
  name: uebungsverwaltung-frontend
  labels:
    app: uebungsverwaltung
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uebungsverwaltung
  template:
    metadata:
      labels:
        app: uebungsverwaltung
    spec:
      containers:
        - name: uebungsverwaltung
          image: ghcr.io/kaf212/uebungsverwaltung_web:v5
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: uebungsverwaltung
  name: frontend-service
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: uebungsverwaltung
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: uebungsverwaltung
  name: uebungsverwaltung
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: frontend-service
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect