apiVersion: apps/v1
kind: Deployment
metadata:
  name: uebungsverwaltung-frontend
  labels:
    app: uebungsverwaltung
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uebungsverwaltung
  template:
    metadata:
      labels:
        app: uebungsverwaltung
    spec:
      containers:
        - name: uebungsverwaltung
          image: rg.fr-par.scw.cloud/namespace-uebungsverwaltung/uebungsverwaltung-nginx:v48
          ports:
            - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: uebungsverwaltung
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

