apiVersion: apps/v1
kind: Deployment
metadata:
  name: uebungsverwaltung-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uebungsverwaltung
  template:
    metadata:
      labels:
        app: uebungsverwaltung
    spec:
      containers:
        - name: uebungsverwaltung
          image: rg.fr-par.scw.cloud/namespace-uebungsverwaltung/uebungsverwaltung-node:v5
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_USER
              value: mongouser
            - name: MONGO_PASSWORD
              value: mongopassword
            - name: MONGO_URI
              value: mongodb://mongo-service.default.svc.cluster.local:27017/dev
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: uebungsverwaltung
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer